-- Brand Extraction database design
CREATE TABLE brands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    domain VARCHAR(500) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE run_brands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_run_id INTEGER NOT NULL REFERENCES ai_runs(id),
    brand_id INTEGER NOT NULL REFERENCES brands(id),
    raw_name VARCHAR(500) NOT NULL,
    rank INTEGER NOT NULL,
    confidence DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_run_brand UNIQUE (ai_run_id, brand_id)
);

CREATE INDEX ix_run_brands_ai_run_id ON run_brands (ai_run_id);
CREATE INDEX ix_run_brands_brand_id ON run_brands (brand_id);
