import random
import time
from fastapi import HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.config import settings
from app.auth.password import get_password_hash
from app.auth.sms_service import sms_client
from app.repositories.user_repository import UserRepository


class OTPStore:
    def __init__(self):
        self._otp: dict[str, dict] = {}
        self._rate_limit: dict[str, float] = {}
        self._attempts: dict[str, int] = {}

    def check_send_rate(self, phone: str) -> None:
        now = time.time()
        last = self._rate_limit.get(phone, 0)
        if now - last < settings.OTP_SEND_COOLDOWN:
            remaining = int(settings.OTP_SEND_COOLDOWN - (now - last))
            raise HTTPException(429, f"لطفاً {remaining} ثانیه صبر کنید")

    def store(self, phone: str, code: str) -> None:
        self._otp[phone] = {"code": code, "expires_at": time.time() + settings.OTP_TTL}
        self._rate_limit[phone] = time.time()
        self._attempts.pop(phone, None)

    def check(self, phone: str, code: str) -> bool:
        stored = self._otp.get(phone)
        if not stored or time.time() > stored["expires_at"]:
            self._otp.pop(phone, None)
            return False
        if stored["code"] != code:
            self._attempts[phone] = self._attempts.get(phone, 0) + 1
            return False
        self._otp.pop(phone, None)
        self._attempts.pop(phone, None)
        return True

    def get_attempts(self, phone: str) -> int:
        return self._attempts.get(phone, 0)


otp_store = OTPStore()


class AuthService:
    def __init__(self, session: AsyncSession):
        self.user_repo = UserRepository(session)
        self.otp_store = otp_store

    @staticmethod
    def _is_dev_otp(phone: str) -> bool:
        return bool(
            settings.DEBUG
            and settings.DEV_OTP_PHONE
            and settings.DEV_OTP_CODE
            and phone == settings.DEV_OTP_PHONE
        )

    def _store_dev_otp(self, phone: str) -> None:
        self.otp_store.store(phone, settings.DEV_OTP_CODE)

    async def register_sms(self, phone: str, first_name: str, last_name: str, email: str | None) -> None:
        if not self._is_dev_otp(phone):
            otp_store.check_send_rate(phone)

        user = await self.user_repo.get_by_phone(phone)
        if not user:
            user = await self.user_repo.create(
                phone=phone,
                email=email,
                first_name=first_name,
                last_name=last_name,
                hashed_password=get_password_hash("sms-only"),
                is_active=True,
            )

        if self._is_dev_otp(phone):
            self._store_dev_otp(phone)
            return

        code = str(random.randint(100000, 999999))
        otp_store.store(phone, code)

        sent = await sms_client.send_otp(phone, code)
        if not sent:
            raise HTTPException(503, "SMS service is temporarily unavailable")

    async def request_sms(self, phone: str) -> None:
        if not self._is_dev_otp(phone):
            otp_store.check_send_rate(phone)

        user = await self.user_repo.get_by_phone(phone)
        if not user:
            raise HTTPException(400, "کاربری با این شماره یافت نشد. لطفاً ابتدا ثبت‌نام کنید")

        if self._is_dev_otp(phone):
            self._store_dev_otp(phone)
            return

        code = str(random.randint(100000, 999999))
        otp_store.store(phone, code)

        sent = await sms_client.send_otp(phone, code)
        if not sent:
            raise HTTPException(503, "SMS service is temporarily unavailable")

    async def verify_sms(self, phone: str, code: str) -> str:
        attempts = otp_store.get_attempts(phone)
        if attempts >= settings.OTP_MAX_ATTEMPTS:
            otp_store._otp.pop(phone, None)
            otp_store._attempts.pop(phone, None)
            raise HTTPException(429, "تعداد تلاش‌ها زیاد بود. مجدداً کد بگیرید")

        if not otp_store.check(phone, code):
            remaining = settings.OTP_MAX_ATTEMPTS - attempts - 1
            if remaining <= 0:
                raise HTTPException(429, "تعداد تلاش‌ها تمام شد. مجدداً کد بگیرید")
            raise HTTPException(400, f"کد اشتباه است. {remaining} تلاش باقی‌مانده")

        user = await self.user_repo.get_by_phone(phone)
        if not user:
            raise HTTPException(404, "کاربر یافت نشد")

        await self.user_repo.mark_verified(user)
        return user  # JWT token will be generated by caller
