/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectManagementRouteImport } from './routes/_authenticated/project-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects_.$id'
import { Route as AuthenticatedProjectsIdManageRouteImport } from './routes/_authenticated/projects_.$id_.manage'
import { Route as AuthenticatedProjectsProjectIdPromptsPromptIdRouteImport } from './routes/_authenticated/projects_.$projectId.prompts.$promptId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectManagementRoute =
  AuthenticatedProjectManagementRouteImport.update({
    id: '/project-management',
    path: '/project-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIdManageRoute =
  AuthenticatedProjectsIdManageRouteImport.update({
    id: '/projects_/$id_/manage',
    path: '/projects/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPromptsPromptIdRoute =
  AuthenticatedProjectsProjectIdPromptsPromptIdRouteImport.update({
    id: '/projects_/$projectId/prompts/$promptId',
    path: '/projects/$projectId/prompts/$promptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project-management': typeof AuthenticatedProjectManagementRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/$id/manage': typeof AuthenticatedProjectsIdManageRoute
  '/projects/$projectId/prompts/$promptId': typeof AuthenticatedProjectsProjectIdPromptsPromptIdRoute
}
export interface FileRoutesByTo {
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project-management': typeof AuthenticatedProjectManagementRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/$id/manage': typeof AuthenticatedProjectsIdManageRoute
  '/projects/$projectId/prompts/$promptId': typeof AuthenticatedProjectsProjectIdPromptsPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/project-management': typeof AuthenticatedProjectManagementRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects_/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects_/$id_/manage': typeof AuthenticatedProjectsIdManageRoute
  '/_authenticated/projects_/$projectId/prompts/$promptId': typeof AuthenticatedProjectsProjectIdPromptsPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/sign-in'
    | '/analytics'
    | '/dashboard'
    | '/project-management'
    | '/projects'
    | '/shared/$token'
    | '/projects/$id'
    | '/projects/$id/manage'
    | '/projects/$projectId/prompts/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/register'
    | '/sign-in'
    | '/analytics'
    | '/dashboard'
    | '/project-management'
    | '/projects'
    | '/shared/$token'
    | '/'
    | '/projects/$id'
    | '/projects/$id/manage'
    | '/projects/$projectId/prompts/$promptId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/register'
    | '/sign-in'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/project-management'
    | '/_authenticated/projects'
    | '/shared/$token'
    | '/_authenticated/'
    | '/_authenticated/projects_/$id'
    | '/_authenticated/projects_/$id_/manage'
    | '/_authenticated/projects_/$projectId/prompts/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-management': {
      id: '/_authenticated/project-management'
      path: '/project-management'
      fullPath: '/project-management'
      preLoaderRoute: typeof AuthenticatedProjectManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects_/$id': {
      id: '/_authenticated/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects_/$id_/manage': {
      id: '/_authenticated/projects_/$id_/manage'
      path: '/projects/$id/manage'
      fullPath: '/projects/$id/manage'
      preLoaderRoute: typeof AuthenticatedProjectsIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects_/$projectId/prompts/$promptId': {
      id: '/_authenticated/projects_/$projectId/prompts/$promptId'
      path: '/projects/$projectId/prompts/$promptId'
      fullPath: '/projects/$projectId/prompts/$promptId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPromptsPromptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectManagementRoute: typeof AuthenticatedProjectManagementRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIdManageRoute: typeof AuthenticatedProjectsIdManageRoute
  AuthenticatedProjectsProjectIdPromptsPromptIdRoute: typeof AuthenticatedProjectsProjectIdPromptsPromptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectManagementRoute: AuthenticatedProjectManagementRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIdManageRoute: AuthenticatedProjectsIdManageRoute,
  AuthenticatedProjectsProjectIdPromptsPromptIdRoute:
    AuthenticatedProjectsProjectIdPromptsPromptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
